###

POST http://localhost:8000/register
Content-Type: application/json

{
    "email": "abdirahman@gmail.com",
    "password": "kms@1234",
    "gender":true,
    "age": 23,
    "name": "abdirahman",
    "phone": 1234567890,
    "location": "somalia",
    "date_of_birth": "2000-01-01",
    "role":"user"
}
###
POST http://localhost:8000/login
Content-Type: application/json

{
    "email": "sadiqueabdirahman@gmail.com",
    "password": "kms@1234"
}
###
POST http://localhost:8000/register
Content-Type: application/json

{
  "email": "abdirahman@gmail.com",
  "password": "kms@1234",
  "gender": true,
  "age": 23,
  "name": "abdirahman",
  "phone": 1234567890,
  "location": "somalia",
  "date_of_birth": "2000-01-01"
}

###
POST http://localhost:3000/vehicle
Content-Type: application/json

{
  "vehicle_id": 2,
  "avalilability":"davailable"
}
###
GET https://jsonplaceholder.typicode.com/posts/1
